apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: hello-world-app:2
        name: hello-world
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      - image: hello-world-app-2:1
        name: hello-world-2
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
